language: node_js
node_js:
- node
- '7'
- '6'
- '5'
- '4'
- '0.12'
notifications:
  email: false
  slack:
    secure: bvnLnD+/2/XlRABQmx8Fp8IbXUM6qrTMM25DZSa4tKx5ueAmEVVuXwxNFLd9RQVLutIHz+Jm/GJ1GdC3aM7TipwbLeXlylqqXD1RjyZCsQVdWAcI9qtagEafuhw1CA8PvRplZAypYk0saC4HvSPduo4N7pn72ERQPmfACv+XpzbrsdjdB4yFASNd0CKJ02Y/o60kRBKuCBkNM47rGgvhD6JGzOp1Yq3ZftkA4pbcR6lmiNer4z/x1opzV0T6qWJ/TMP3aHsm9UhfBqyqEl9c8OD8PaxMppMbWc5bN50+zgNILeEVMPMRqv3+THeV2hLIcyLo9MCDrBxRza/xhIij09+9As7IzFfPIrZ+6ZrzDLAZAkiJ4I3GQlLAD2NrC+lJdkcw6i2z+DEF4Xig0v3JbPAfw7/0of+jF2mxAhpFXSo5hg3ViLvgTsaam4UHtvVh1zF/oGoeMtHf3nGJtN0bDK/w3rDV/8bq9/dHI0IdzjWzsX6GWsR3OMFpUCo6Qev78PoboHDRrqDq7UsQ8sMo5aPGTDSDQPww4iysc0msdOatIDrhj/h66gzUf4nbbPJxeh9oiOFGrW/5csAOW+9/t4BMWW1sA4Kc3mcLYz2NYuxSGTNV6Xzm49PtuHfkiUuX4ZV9hUgf9nN5H+YPFitmKAXPwQj5z+kS0DNPEyUfqy8=
