language: node_js
node_js:
- node
- '7'
- '6'
- '5'
- '4'
- '0.12'
notifications:
  email: false
  slack:
    secure: rToTt59CI/pHBgoF5L8Tb77PbPWWZhA8jJwK4X+m8xy04dHKLb9KaT/TOHd5MqP1FhmAsx/wrgZa7/p6z7M2pHAvrRm5YezntRR2xVWcbyfZ9D98tWRXKzKjcuJg6FP70ndFT30ni2qZmRSoj0Nx/rQMbf5wBABWhm8V0n6Wkfqo4mfq51ehvqfjDWmmYYqmTPcq9o2s0pbfo7n/UwGUrap1iIQzjRciuv+z6UDpWjp4SxfCDTHaNqDMnXzJKgAMzK9NtZs4FOFiZAqZcCQ5Fh7S/M7Hz9fcCdui8MEzlgczMrprBnKqQcxOTIly7bTtH/FEjwBT6nVGCrY1m17ec9n/D4ieUmKvfbmzvB4Kw8dVEi64M6pPUKevXoIn1G+AkT7OdNQEKs3FLxaZHnrxdGzGDNxfwit81DfSkpDBD0QoTroHoS621NG1Fl1KQNZc/qOOJt93hRiDGn/qyumAvcfACQUPp+MkZg+eNf5jbEuRIWAzCsaap3H1ajKWgfsYef9ekNi8o9gLem5ynPjqzrYw5v5nhBxCC7Rx+0I3eLMNa8MIwbE/tnTlkV1mPk5zA8py7Mv61Gewj02YDzemesSJS5p33MtRk/k5tenrkbpXyNEvmQNh9JYJDGKh166ryDzSEUJxEbEALutP57HYI8xdixn5iQ9GrZ/ixtPp96c=
